---
source_directory: "spec/infra/harness"
state_file: "%{hiera('project_directory')}/state/harness.tfstate"

vars:
  region: "%{hiera('region')}"

  component: "%{hiera('component')}"
  deployment_identifier: "%{hiera('deployment_identifier')}"

  idle_timeout: "%{hiera('idle_timeout')}"

  expose_to_public_internet: "%{hiera('expose_to_public_internet')}"

  dns: "%{hiera('dns')}"
  target_groups: "%{hiera('target_groups')}"
  listeners: "%{hiera('listeners')}"
